receivers:
  otlp:
    protocols:
      http:
      grpc:

  prometheus:
    config:
      scrape_configs:
        - job_name: 'postgres-exporter'
          static_configs:
            - targets: ['postgres-exporter:9187']

exporters:
  logging:
    loglevel: debug

  jaeger:
    endpoint: jaeger:14268
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [jaeger, logging]

    metrics:
      receivers: [prometheus]
      exporters: [logging]
